### ISSUE TITLE
Interop with go-ipfs for current protocols

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-swarm#62]
At the moment we are using [protocol-buffers-stream](https://github.com/mafintosh/protocol-buffers-stream) for handling some of the stream things with protobufs. These are incompatible though with the way go-ipfs sends msgs using [gogo/protobuf/io](https://github.com/gogo/protobuf/tree/master/io). 

Ways to resolve this

1. Make a PR to protocol-buffers-stream which enables compatibility using an option
2. Implement our own stream handling
3. ??? 

The main issues are

1. protocol-buffers-stream does an initial handshake, but we can disable this already
2. protocol-buffers-stream sends a message id between the frame length and the actual message, which gogo does not.

**Comment by dignifiedquire** [comment]
I just found https://github.com/mafintosh/length-prefixed-stream which could be another option for us to use

**Comment by dignifiedquire** [comment]
cc @diasdavid

**Comment by diasdavid** [comment]
We use length-prefixed-stream on multistream https://github.com/diasdavid/js-multistream/blob/master/package.json#L41 and it seems to be the right way to do here too, since it follows the https://github.com/jbenet/multistream/tree/master/lpm-stream spec. (lpm-stream is msg-io)

We just need to length-prefix our protobufs :)

**Comment by dignifiedquire** [comment]
sounds good it's what I will be using in secio as well

**Comment by diasdavid** [comment]
This has been taken care of a while ago :)
